baseURL = "https://example.com"

[author]
    name = "Bjørn Erik Pedersen"

[taxonomies]
    category = 'categories'

[caches]
    [caches.images]
        dir    = ':cacheDir/galleriesdeluxe'
        maxAge = "4320h"                     # 6 months.

[params]
    [params.gallerydeluxe]
        shuffle     = false
        reverse     = true
        enable_exif = false
    [params.galleriesdeluxe]
        gallery_section = "galleries"
        galleries_alias = "collections"
        [params.galleriesdeluxe.sassvars]
            color_background      = "#08061c"
            color_background_dark = "#08061c"
            color_text_dark       = "#ffffff"
            color_link_dark       = "#4586d5"
            color_background_light = "#c5c2bdf2"
            color_text_light       = "#000000"
            color_link_light       = "#2e299d"
            font_family_base       = '"Open Sans", "Gill Sans Nova", Ubuntu, Calibri, "DejaVu Sans", sans-serif'
            font_size_base         = "16px"

[module]
    [module.hugoVersion]
        min = "0.156.0"
    [[module.mounts]]
        source = "assets"
        target = "assets"
    [[module.mounts]]
        source = "layouts"
        target = "layouts"
    [[module.mounts]]
        source = "i18n"
        target = "i18n"
    [[module.mounts]]
        source = "static"
        target = "static"
    [[module.imports]]
        path = "github.com/toozej/gallerydeluxe"
    [[module.imports]]
        path = "github.com/bep/hugo-mod-misc/common-partials"
