name        = "Galleries Deluxe"
license     = "MIT"
licenselink = "https://github.com/toozej/galleriesdeluxe/blob/main/LICENSE"
description = "Multi gallery theme suitable for photography portfolio sites with large galleries."
homepage    = "https://github.com/toozej/galleriesdeluxe"
demosite    = "https://toozej.github.io/galleriesdeluxe/"
tags        = ["galleries", "gallery", "sass"]
min_version = "0.156.0"
[author]
  name     = "toozej"
  homepage = "https://github.com/toozej"

[original]
  author   = "Bjørn Erik Pedersen"
  homepage = "https://bep.is"
  repo     = "https://github.com/bep/galleriesdeluxe"
  demosite = "https://galleriesdeluxe.netlify.app/"
